blank_issues_enabled: true
contact_links:
  - name: WynnBuilder
    url: https://github.com/wynnbuilder/wynnbuilder.github.io/issues
    about: Problems with WynnBuilder itself or its item data belong there.
